services:
  quant_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock_analyzer
    environment:
      - APP_ENV=${APP_ENV:-prod}
      - TZ=Asia/Shanghai
      - http_proxy= 
      - https_proxy=
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    logging:
      driver: "json-file"       # 官方默认驱动
      options:
        max-size: "10m"         # 单个日志文件最大 10MB
        max-file: "3"           # 最多保留 3 个旧日志文件（旧的会被自动覆盖）
    volumes:
      - .:/app              # 将当前代码目录映射到容器
      - /Users/weihe/stock/stock_datas:/app/stock_datas
      - /Users/weihe/stock/secret_config:/app/secret_config:ro #敏感信息配置文件映射
    working_dir: /app
    # 使用变量替换，格式为 ${变量名:-默认值}
    command: python jobStarter.py

  # 2. 图形化展示程序
  dashboard:
    build:
      context: .
      dockerfile: streamlit_code/Dockerfile
    container_name: stock_dashboard
    ports:
      - "8501:8501"
    environment:
      - APP_ENV=${APP_ENV:-prod}
      - TZ=Asia/Shanghai
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_CORS_CHECK=false  # 方便 iPad/MacPro 远程访问
    volumes:

      - /Users/weihe/stock/stock_datas:/app/stock_datas:ro  # ro表示只读挂载，保护数据安全
      - /Users/weihe/stock/secret_config:/app/secret_config:ro #敏感信息配置文件映射
    depends_on:
      - quant_bot
    restart: always


